#ifndef _H_PRECEDENCE
#define _H_PRECEDENCE

enum {
    PRECEDENCE_DEFAULT = 0,
    PRECEDENCE_SUM,
    PRECEDENCE_MULT,
    PRECEDENCE_POWER,
    PRECEDENCE_GROUP,
    PRECEDENCE_ASSIGNMENT
};

#endif
