#pragma once

enum TOKENTYPE {
    TOKEN_NAME, TOKEN_NUMBER,
    TOKEN_ADDITION, TOKEN_NEGATION, TOKEN_MUILTIPLICATION, TOKEN_DIVISION,
    TOKEN_POWER, TOKEN_REMAINDER, TOKEN_OPEN_BRACKET, TOKEN_CLOSE_BRACKET
};

struct TOKEN {
    TOKENTYPE type;
    size_t value_length;
    char* value;
};
